[package]
name = "learn-bitcoin-rs-macros"
version = "0.1.0"
authors = ["Martin Jones <murtin.jones@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"

[dependencies.syn]
version = "1.0"
features = ["parsing"]
